### ISSUE TITLE
[Task] Finalização da Compra/Venda de Ativos

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#110]
### O que precisa ser feito?
- Arrumar estilização da busca de ativos
- Arrumar integração de compra/venda com nova versão do backend
- Estilização do botão de sair da sidebar

### Por que precisa ser feito?
Finalizar completamente a tela de compra/venda de ativos

### Tasks

- [x] Estilização da busca de ativos
- [x] Integração compra/venda
- [x] estilização botão sair sidebar

**Comment by luciano-freitas-melo** [comment]
Encontrado um bug quando estava fazendo a integração #111
