### ISSUE TITLE
[Task] Desenvolver documento de visão

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#18]
Relacionada a issue #13

### O que precisa ser feito?
Desenvolver o documento de visão do projeto, levando em conta todas as informações já obtidas sobre o mesmo, e publicá-lo no gitpages do projeto

#### Tasks
- [x] Fazer markdown do docs
- [x] Subir o documento para o gitpages

@luciano-freitas-melo 
- [x] Introdução
- [x] Posicionamento
- [x]  Descrição da Parte Interessada e do Usuário

@lucasfs1007 
- [x] Visão Geral do Produto
- [x] Recursos do Produto
- [x] Restrições
- [x] Requisitos

### Por que precisa ser feito?
O documento de visão é essencial no desenvolvimento de um software, pois servirá de guia para o entendimento do produto a ser desenvolvido.

### Critério de Aceitação

**Dada(o)** o documento de visão já desenvolvido previamente
**Quando** for implementado com todas as informações relevantes e passado para markdown
**Então** deverá ser possível acessá-lo pelo gitpages do projeto

### Informações Adicionais
[Documento de Visão](https://docs.google.com/document/d/1broVsDziA_sq2-kM4O2j_nLhxF1yDg8OqElE8ARDVrs/edit?usp=sharing)

**Comment by lucasfs1007** [comment]
REVISÃO:
 -Adiciona visão geral do produto.
-Adiciona recursos do produto
-Adiciona restrições
-Adiciona requisitos
@luciano-freitas-melo valida a entrega por favor

**Comment by zjosuez** [comment]
Criei uma nova branch "Markdown" e subi o documento de visão em markdown lá. O arquivo pode conter alguns erros, realizem as alterações que vocês acharem necessárias.

**Comment by luciano-freitas-melo** [comment]
Finalizado a parte do documento de visão que faltava, só peço que deixem a parte de requisitos por fora por enquanto, pois irei revisar algumas coisas antes de colocar no documento!
