### ISSUE TITLE
[US 01]  Página de Cadastro de Usuário

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#30]
### 📗 Resumo
**Como** investior
**Eu quero/desejo** me cadastrar na plataforma
**Para** conseguir logar no Invext e utilizar das funcionalidades do site
 
#### Critério de Aceitação 1
**Dada(o)** a prototipação do projeto
**Quando** houver a criação da página de cadastro de usuário
**Então** seja possível visualizar a página como está no protótipo

#### Critério de Aceitação 2
**Dada(o)** página de cadastro de usuário
**Quando** o usuário digitar os inputs para se cadastrar
**Então** deve-se guardar esses valores em variáveis no react

#### Critério de Aceitação 3
**Dada(o)** página de cadastro do usuário
**Quando** o usuário errar alguma validação dos inputs
**Então** será apresentada um popup de erro, com a mensagem que ocorreu
 
### 🖌Design
![Página de Cadastro](https://images.zenhubusercontent.com/612e94cf0aa9b5314c653695/72a63f19-0309-4195-b33d-218df386f846)
 
#### Link para Figma
[Link para a página do figma](https://www.figma.com/file/GWE5C8yo9JrKad3GFunhmk/Prot%C3%B3tipo-Invext?node-id=43%3A196)
 
#### Links
[Documento de Arquitetura](https://fga-eps-mds.github.io/GFour-Invext/#/pages/DocumentoDeArquiteturaDeSoftware)

###  🚩ToDo
- [x] Página de Cadastro de Usuário
- [x] Guardar variáveis dos inputs
- [x] Popup para mensagem de erro

**Comment by lucasfs1007** [comment]
- Eu e o Luciano estamos produzindo essa tela tela utilizando pareamento com a extensão "live share" do vs code

**Comment by lucasfs1007** [comment]
@antonioleaojr @amanda-noda  deem uma revisada na branch develops pq o commit foi junto com o fechamento da última pull request por algum motivo. Então temm que dar uma olhada por lá
