### ISSUE TITLE
Time todo

### ISSUE THREAD

**Issue by MariaAbritta** [fga-eps-mds/GFour-Invext#7]
🫂 Entender mais... 🫂
Com a decisão do nosso tema, ir atrás de entender um pouco mais sobre e fazer suas pesquisas de acordo com os subgrupos.

- [x] ◍ Forms de Pergunta 
Conversar sobre pessoas interessadas na aplicação, o que elas gostariam que tivesse.
@LeonardoPadre e @lucasgcaldas 

- [x] ◍ Miro 
Configuração do Miro para a utilização do Board.
   - [x]  Amanda
   - [x] Luciano
   - [x] Lucas Gomes
   - [x] Antônio
   - [x] Maria Abritta
   - [x] Leo
   - [x] Lucas
   - [x] Josué

- [x] ◍ Documento de visão 
Pesquisa o que tem que ter no documento (rascunho pronto)
@luciano-freitas-melo e @lucasfs1007 

- [x] ◍ Documento de arquitetura 
Pesquisa o que tem que ter no documento
@lucasgcaldas , @amanda-noda , @zjosuez , @antonioleaojr e @LeonardoPadre 

- [x] ◍ TAP
Pesquisa o que tem que ter no documento e desenvolver
@MariaAbritta

- [ ] ◍ GitPages
Finalizar até domingo (26/06)
@MariaAbritta

**Comment by luciano-freitas-melo** [comment]
### Mudanças na Issue
Pessoal,
Mudei algumas coisas na issue:
1. Controle de Riscos
- Falei com a professora sobre o Documento de Riscos e ela disse que não era para a gente fazer por agora, pois ela vai passar um modelo para nas aulas posteriormente.
- Por conta disso, é mais certo a gente não se preocupar com isso agora. Assim, eu tomei a liberdade para realocar o pessoal que estava com essa parte para o Documento de Arquitetura, que foi me informado que será um pouco mais complexo do que o esperado.
2. TAP
- Foi falado durante a aula de quinta (23/06) que seria preciso ter um Termo de Abertura de Projeto (TAP), e a Abritta me falou que ela já havia feito esse tipo de documento antes. Logo, ficou acertado que ela faria esse documento ao invés do Documento de Arquitetura nessa sprint

Essas foram as alterações dessa issue, caso vocês tenham algo para acrescentar ou que podemos mudar, me enviem mensagem para discutirmos sobre isso, pode ser por aqui mesmo no github (bom que fica documentado), mas também no telegram!
