### ISSUE TITLE
[US 13] Integração do auth do back no frontend

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#86]
### 📗 Resumo
**Como** [Quem?]
**Eu quero/desejo** [O que?]
**Para** [Por quê?]

###  🚩ToDo
- [x] Puxar o token do front direto para o "auth" do backend
- [ ] Input de preço não está indo com a vírgula decimal
- [ ] validar quantidade igual a 0
