### ISSUE TITLE
Time todo

### ISSUE THREAD

**Issue by luciano-freitas-melo** [fga-eps-mds/GFour-Invext#9]
### Github

@luciano-freitas-melo @amanda-noda @MariaAbritta @zjosuez @lucasgcaldas @LeonardoPadre @lucasfs1007 @antonioleaojr 
- [x]  Estudar e aplicar Markdown
- [x] Amanda / Gomes / Josué - Doc. Arquitetura
- [ ] Luquinhas / Luciano - Doc. Visão
- [x] Antônio / Léo - TAP (não está no github: [docs TAP](https://docs.google.com/document/d/1nrbSR8SBGZy1AepQZveQ4Snur46dd_PbB-kCfjFzgq4/edit?usp=sharing)

### Termo de Abertura do Projeto (TAP)
- [x]  Acrescentar informações no TAP
- [x] Escopo do projeto
- [ ] Responsabilidades do Scrum Team

@MariaAbritta
- [x] Git Pages

@luciano-freitas-melo 
- [ ] Templates de issue no github
- [x] Criar teams de desenvolvimento para Assignees

### Escopo do Produto
@amanda-noda @antonioleaojr
- [x] Definir o escopo do produto

### Documento de Arquitetura
@amanda-noda @lucasgcaldas 
- [x]  Documento de Requisitos
Notas: 
- [x] Rascunho do que deve ter nos requisitos já está descrito
link do doc: https://unbarqdsw2020-2.github.io/2020.2_G5_EasyCoffee/#/entrega4/das

#### Diagramas UML (+dificuldade)
(?) Quais diagramas tem que haver no projeto?

@lucasgcaldas  @lucasfs1007 
- [ ] Diagrama de Classes (para próxima sprint)

@zjosuez @LeonardoPadre 
- [ ] Diagrama de Pacotes (próxima sprint)

@luciano-freitas-melo @MariaAbritta 
- [ ] Pesquisa sobre os outros diagramas que devem ter no projeto

### Documento de Visão
@luciano-freitas-melo 
- [ ] Desenvolver o documento de visão

**Comment by luciano-freitas-melo** [comment]
Hey @LeonardoPadre @zjosuez @MariaAbritta I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/g4---mds-62ae0e2458c26d001a36c995/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by amanda-noda** [comment]
Só lembrando que o documento de requisitos foi desenvolvido por mim e pelo @lucasgcaldas, na issue estava designada somente para mim.
